### ISSUE TITLE
Add Code for Any Question Related to Linked List Data Structure

### ISSUE THREAD

**Issue by lucy2512** [sigma3labs/Sigma3-DSA-Marathon#10]
Please go through the [rules](https://github.com/sigma3labs/Sigma3-DSA-Marathon/blob/main/CONTRIBUTING.md) from the repository before making any PR📝

**In our repo we are accepting only One PR from each participant so if you are assigned for a task previously int this repo then please do not ask to assign yourself again** 🙂

Also mention the language in which you want to add code 👨‍💻

Other maintainers:- @rajdeep-ghosh @DEBADYUTI-KARMAKAR 

Keep contributing !

**Comment by tvermaashutosh** [comment]
@lucy2512 Please assign it to me.

**Comment by lucy2512** [comment]
Please read the Issue description.
You have already contributed in this repo.

**Comment by Diptigit11** [comment]
I would like to contribute in the Java Language

**Comment by lucy2512** [comment]
You guys can make a PR if you are contributing to this repo for the very first time.
In this case, we will definitely merge your request no need to ask for being assigned.
We will asiign you in the time of merging the PR.
