### ISSUE TITLE
Add Code for Any Question from Leetcode

### ISSUE THREAD

**Issue by lucy2512** [sigma3labs/Sigma3-DSA-Marathon#16]
Please go through the [rules](https://github.com/sigma3labs/Sigma3-DSA-Marathon/blob/main/CONTRIBUTING.md) from the repository before making any PR📝

**In our repo we are accepting only One PR from each participant so if you are assigned for a task previously int this repo then please do not ask to assign yourself again** 🙂

Add the code in the right file
Also mention the question & language in which you want to add code 👨‍💻

Other maintainers:- @DEBADYUTI-KARMAKAR @rajdeep-ghosh 
And also the check if solution is previously present then try to add another problem

Keep contributing !

**Comment by Harinichalla20** [comment]
!assign

**Comment by W41K3R0** [comment]
!assign

**Comment by AbaiKumar** [comment]
Assign me. I like to contribute dynamic programming problems..

**Comment by pandeydhruv2001** [comment]
Please assign this issue I want to add code.

**Comment by devvkumar** [comment]
Please assign this issue I want to add code.

**Comment by AckermanLevi1** [comment]
@lucy2512 I would love to contribute in it

**Comment by Abhii-07** [comment]
Hey @lucy2512 , I would love to contribute by adding a LC Medium question to this. I recently faced this question in an interview. Can you please assign me? 
Thanks!

**Comment by ArcheR1901** [comment]
please assign, I would love to contribute

**Comment by lucy2512** [comment]
You guys can make a PR if you are contributing to this repo for the very first time.
In this case, we will definitely merge your request no need to ask for being assigned.
We will asiign you in the time of merging the PR.

**Comment by devvkumar** [comment]
Done #16 Please Merge it

**Comment by pandeydhruv2001** [comment]
Hey @lucy2512,opened PR #22. Please merge.

**Comment by ArcheR1901** [comment]
Hello, PR #29 opened, please merge

**Comment by ShrutiShrivastava0613** [comment]
PR #36 opened, please merge my request.

**Comment by pandeydhruv2001** [comment]
PR #39 opened,please review and merge

**Comment by HimanshuGitCode** [comment]
#61 and #62 please check and merge
