### ISSUE TITLE
Add Binary Search Code 

### ISSUE THREAD

**Issue by lucy2512** [sigma3labs/Sigma3-DSA-Marathon#2]
Please go through the [rules](https://github.com/sigma3labs/Sigma3-DSA-Marathon/blob/main/CONTRIBUTING.md) from the repository before making any PR📝
Also mention the language in which you want to add code 👨‍💻
In our repo we are accepting only One PR from each participant so if you are assigned for a task previously int this repo then please do not ask to assign yourself again 🙂
Keep contributing !

Other maintainers:- @rajdeep-ghosh @DEBADYUTI-KARMAKAR

**Comment by alienishi** [comment]
Please assign this issue to me

**Comment by Abhishekgupta204** [comment]
Please assign this issue to me @lucy2512 .
I can write this in Java.

**Comment by Arcturus22** [comment]
@lucy2512 
Please assign me this issue. I can add the code in Javascript.

**Comment by rajdeep-ghosh** [comment]
> Please assign this issue to me @lucy2512 I can write this in C++ and Python

@alienishi  One can contribute in any one programming language

**Comment by alienishi** [comment]
@rajdeep-ghosh Ok i'll add the code in C++

**Comment by rajdeep-ghosh** [comment]
@Arcturus22 @Abhishekgupta204 both of you were assigned to a different issue #1 so you cannot contribute in this issue

**Comment by rajdeep-ghosh** [comment]
@alienishi sure go for it

**Comment by muskanv021** [comment]
please assign me this task.

**Comment by AckermanLevi1** [comment]
@lucy2512 I would love to contribute in Python

**Comment by lucy2512** [comment]
You guys can make a PR if you are contributing to this repo for the very first time as we are accepting only one PR from each contributor to give chance everyone.
In this case, we will definitely merge your request no need to ask for being assigned.
We will asiign you in the time of merging the PR.
