### ISSUE TITLE
LeectCode Problem

### ISSUE THREAD

**Issue by tanisha91** [sigma3labs/Sigma3-DSA-Marathon#46]
Hey.. I wanted to add one Leetcode question..
Please assign it to me

**Comment by gauravbhaskar080** [comment]
Hi, Please assign this issue to me , because this is my first time in hacktoberfest !!!
And I have completed 260+ questions in LeetCode !!!

**Comment by DEBADYUTI-KARMAKAR** [comment]
@tanisha91 @gauravbhaskar080 [https://github.com/sigma3labs/Sigma3-DSA-Marathon/issues/16](url)
