### ISSUE TITLE
Design a JavaScript function that will work like map function in JavaScript.

### ISSUE THREAD

**Issue by DEBADYUTI-KARMAKAR** [sigma3labs/Sigma3-DSA-Marathon#50]
Please go through the [rules](https://github.com/sigma3labs/Sigma3-DSA-Marathon/blob/main/CONTRIBUTING.md) from the repository before making any PR📝
Also mention the language in which you want to add code 👨‍💻
In our repo we are accepting only One PR from each participant so if you are assigned for a task previously int this repo then please do not ask to assign yourself again 🙂
Keep contributing !

Other maintainers:- @rajdeep-ghosh @lucy2512

**Comment by mhdamaan79** [comment]
I would like to work on this issue. Please assign this issue to me.

**Comment by DEBADYUTI-KARMAKAR** [comment]
@mhdamaan79  sure go for it
