### ISSUE TITLE
Design a JavaScript function that will work like filter function in JavaScript. 

### ISSUE THREAD

**Issue by DEBADYUTI-KARMAKAR** [sigma3labs/Sigma3-DSA-Marathon#58]
Please go through the [rules](https://github.com/sigma3labs/Sigma3-DSA-Marathon/blob/main/CONTRIBUTING.md) from the repository before making any PR📝
Also mention the language in which you want to add code 👨‍💻
In our repo we are accepting only One PR from each participant so if you are assigned for a task previously int this repo then please do not ask to assign yourself again 🙂
Keep contributing !

Other maintainers:- @rajdeep-ghosh @lucy2512

**Comment by abhinab-choudhury** [comment]
can you please proved some more information related to the filter function

**Comment by Sairajepawar** [comment]
I would like to work on this, but can elaborate logic/condition for filter.

**Comment by shivaram19** [comment]
can you please assign this task to me ,I'm assuming the filter function is for search bar component ?

**Comment by vishal-rathod-07** [comment]
!assign

**Comment by DEBADYUTI-KARMAKAR** [comment]
Implement our own Array.filter() method in JavaScript. @vishal-rathod-07 @Sairajepawar @shivaram19 @abhinab-choudhury 
1st PR will be accepted.
